### ISSUE TITLE
How about telling readme that there is dependency on libev?

### ISSUE THREAD

**Issue by johlim** [dhess/echoev#1]
How about telling readme that there is dependency on libev?

+++ b/echoev.c
@@ -41,7 +41,7 @@
 #include <getopt.h>
 #include <libgen.h>
 #include <assert.h>
-#include <ev.h>

**precondition**

sudo apt install libev-dev

**Comment by dhess** [comment]
Literally, the first paragraph of the README says:

> echoev is a simple TCP echo server, <strong>built on libev</strong>. It has several options; run ‘echoev –help’ for usage.

Also, the project is named echo<strong>ev</strong>.

I don't know how much more clear it could be.
